package com.unionsg.xaccounting.enums;

public enum DocumentModule {
    INVOICE,
    PAYMENT,
    CREDIT_NOTE,
    QUOTE,
    PURCHASE_ORDER,
    JOURNAL,
    ACCOUNT,
    DOCUMENT_TEMPLATE_INVOICE,
    DOCUMENT_TEMPLATE_QUOTE,
    DOCUMENT_TEMPLATE_PURCHASE_ORDER,
    DOCUMENT_TEMPLATE_CREDIT_NOTE,
    DOCUMENT_TEMPLATE_DELIVERY_NOTE,
    DOCUMENT_TEMPLATE_RECEIPT
}
