package com.unionsg.xaccounting.enums;

public enum EntityType {
    INVOICE,
    CUSTOMER,
    SUPPLIER,
    PAYMENT,
    EXPENSE,
    PRODUCT,
    COMPANY,
    USER,
    GENERATED_DOCUMENT,
    DOCUMENT_TEMPLATE_INVOICE,
    DOCUMENT_TEMPLATE_QUOTE,
    DOCUMENT_TEMPLATE_PURCHASE_ORDER,
    DOCUMENT_TEMPLATE_CREDIT_NOTE,
    DOCUMENT_TEMPLATE_DELIVERY_NOTE,
    DOCUMENT_TEMPLATE_RECEIPT,
    GENERAL_JOURNAL,
    SALES_JOURNAL,
    PURCHASE_JOURNAL,
    PAYROLL_JOURNAL,
    ADJUSTMENT_JOURNAL,
    OPENING_BALANCE_JOURNAL,
    CLOSING_JOURNAL,
    REVERSING_JOURNAL
}
