spring.application.name=xaccounting

# server
server.port=8080

# =============================
# PostgresSQL Datasource
# =============================
spring.datasource.url=jdbc:postgresql://localhost:5432/xaccounting
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================
# JPA / Hibernate
# =============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable swagger UI and API
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html